version: '3.9'

services:
  jpcc-u20-build-release:
    image: jpcc:u20-build-release
    build:
      context: .
      target: jpcc-u20-build-release

  jpcc-u20-build-debug:
    image: jpcc:u20-build-debug
    build:
      context: .
      target: jpcc-u20-build-debug
