version: '3.9'

services:
  build-test-release:
    extends:
      file: docker/templates.yml
      service: build-test
    container_name: build-test-release
    environment:
      - BUILD_TYPE=Release

  build-test-debug:
    extends:
      file: docker/templates.yml
      service: build-test
    container_name: build-test-debug
    environment:
      - BUILD_TYPE=Debug
