version: '3.9'

services:
  _build-image:
    image: mpeg-pcc-tmc2:15
    build:
      context: .
      target: mpeg-pcc-tmc2-build
    command: [ 'echo', 'build completed' ]
  CWAI:
    image: mpeg-pcc-tmc2:15
    depends_on:
      - _build-image
    container_name: CWAI
    command: [ "bash","CWAI.sh" ]
    volumes:
      - "../../../../dataset:/dataset"
      #      - "../../../../result/mpeg-pcc-tmc2/S22CWAI_queen:/mpeg-pcc-tmc2/S22CWAI_queen"
      - "../../../../result/mpeg-pcc-tmc2/S23CWAI_loot:/mpeg-pcc-tmc2/S23CWAI_loot"
      - "../../../../result/mpeg-pcc-tmc2/S24CWAI_redandblack:/mpeg-pcc-tmc2/S24CWAI_redandblack"
      - "../../../../result/mpeg-pcc-tmc2/S25CWAI_soldier:/mpeg-pcc-tmc2/S25CWAI_soldier"
      - "../../../../result/mpeg-pcc-tmc2/S26CWAI_longdress:/mpeg-pcc-tmc2/S26CWAI_longdress"
      #      - "../../../../result/mpeg-pcc-tmc2/S27CWAI_basketball:/mpeg-pcc-tmc2/S27CWAI_basketball"
      #      - "../../../../result/mpeg-pcc-tmc2/S28CWAI_dancer:/mpeg-pcc-tmc2/S28CWAI_dancer"
    deploy:
      resources:
        limits:
          cpus: "1"